ALTER TABLE assessments
    ALTER COLUMN axis_left     TYPE INTEGER         USING axis_left::INTEGER,
    ALTER COLUMN axis_right    TYPE INTEGER         USING axis_right::INTEGER,
    ALTER COLUMN sphere_left   TYPE DOUBLE PRECISION USING sphere_left::DOUBLE PRECISION,
    ALTER COLUMN sphere_right  TYPE DOUBLE PRECISION USING sphere_right::DOUBLE PRECISION,
    ALTER COLUMN cylinder_left TYPE DOUBLE PRECISION USING cylinder_left::DOUBLE PRECISION,
    ALTER COLUMN cylinder_right TYPE DOUBLE PRECISION USING cylinder_right::DOUBLE PRECISION,
    ALTER COLUMN iop_left      TYPE DOUBLE PRECISION USING iop_left::DOUBLE PRECISION,
    ALTER COLUMN iop_right     TYPE DOUBLE PRECISION USING iop_right::DOUBLE PRECISION;
